version: "3"
services:
  server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
  client:
    build: .
    ports:
      - "8502:8501"
    command: streamlit run client.py
    depends_on:
      - server
